#!/bin/bash -e

export DKR_NAME="$(basename $0)"
if [ "${DKR_HOME}" == "" ]; then
	export DKR_HOME=~/.dkr
fi

if [ "${DKR_DOCKER_COMMAND}" == "" ]; then
	export DKR_DOCKER_COMMAND=docker
fi

export DKR_COMMAND="$1" #TODO: it's possible that the command isn't the first arg

function debug {
	if [ "${DKR_DEBUG}" != "" ]; then
		echo "$@" >&2
	fi
}

function err {
	echo "$@" >&2
}

function usage {
	echo "Dkr - Extendable docker cli wrapper"
	echo ""
	echo "Dkr exposes all the standard docker commands:"

	"${DKR_DOCKER_COMMAND}" --help | sed "s:docker COMMAND --help:${DKR_NAME} COMMAND --help:g" | tail -n +3 | tail -n +5

	echo ""
	echo "Extensions:"
	echo ""

	for option in $(declare -F | grep -Eo "dkr-.*"); do
		if [[ "${option}" != *-summary_ ]] && [[ "${option}" != *-help_ ]]; then
			set +e
			2>/dev/null 1>/dev/null type "${option}-summary_"
			exitCode=$?
			set -e

			if [ "${exitCode}" == "0" ]; then
				echo "    ${option:4} - $(eval ${option}-summary_)"
			else
				echo "    ${option:4}"
			fi
		fi
	done

	echo ""
	echo "See README for more information on extending dkr"
}

if [ "${DKR_COMMAND}" == "" ]; then
	usage
	exit 1
fi

set +e
2>/dev/null 1>/dev/null type "dkr-${DKR_COMMAND}"
exitCode=$?
set -e

if [ "$exitCode" == "0" ]; then
	if [[ "$@" =~ '--help' ]]; then
		helpcommand="dkr-${DKR_COMMAND}-help_"

		set +e
		2>/dev/null 1>/dev/null type "${helpcommand}"
		exitCode=$?
		set -e

		if [ "${exitCode}" == "0" ]; then
			eval "${helpcommand}"
		else
			echo "No help available for $DKR_NAME ${DKR_COMMAND}"
			exit 2
		fi
	else
		command="dkr-${DKR_COMMAND}"
		shift
		eval "${command}" "$@"
	fi
else
	if [[ "$@" =~ '--help' ]]; then
		"${DKR_DOCKER_COMMAND}" "$@" | sed "s#Usage:\s*docker#Usage:  ${DKR_NAME}#g"
	else
		"${DKR_DOCKER_COMMAND}" "$@"
	fi
fi
