#!/bin/bash -e

function debug {
	if [ "${DKR_DEBUG}" != "" ]; then
		echo "DEBUG: $@" >&2
	fi
}
export -f debug

function err {
	echo "$@" >&2
}
export -f err

function find_command {
	debug "called find_command"
	for arg in "$@"; do
		if [[ "${arg}" == -* ]]; then
			debug "not using ${arg}"
			continue
		else
			debug "using ${arg}"
			echo "${arg}"
			break
		fi
	done
}

function usage {
	echo "Dkr - Extendable docker cli wrapper"
	echo ""
	echo "Dkr exposes all the standard docker commands:"

	"${DKR_DOCKER_COMMAND}" --help | sed "s:docker COMMAND --help:${DKR_NAME} COMMAND --help:g" | tail -n +3 | tail -n +5

	echo ""
	echo "Extensions:"
	echo ""

	for option in $(declare -F | grep -Eo "__dkr-.*"); do
		if [[ "${option}" != *-summary_ ]] && [[ "${option}" != *-help_ ]]; then
			set +e
			2>/dev/null 1>/dev/null type "${option}-summary_"
			exitCode=$?
			set -e

			if [ "${exitCode}" == "0" ]; then
				echo "    ${option:6} - $(eval ${option}-summary_)"
			else
				echo "    ${option:6}"
			fi
		fi
	done

	echo ""
	echo "See README for more information on extending dkr"
}

export DKR_NAME="$(basename $0)"
if [ "${DKR_HOME}" == "" ]; then
	export DKR_HOME=~/.dkr
fi

if [ "${DKR_DOCKER_COMMAND}" == "" ]; then
	export DKR_DOCKER_COMMAND=docker
fi
export DKR_COMMAND="$(find_command "$@")"

debug "found command: $DKR_COMMAND"

if [ "${DKR_COMMAND}" == "" ]; then
	usage
	exit 1
fi

debug "Checking for: __dkr-${DKR_COMMAND}"
set +e
2>/dev/null 1>/dev/null type "__dkr-${DKR_COMMAND}"
exitCode=$?
set -e

if [ "$exitCode" == "0" ]; then
	debug "Using dkr command"
	if [[ "$@" =~ '--help' ]]; then
		helpcommand="__dkr-${DKR_COMMAND}-help_"

		set +e
		2>/dev/null 1>/dev/null type "${helpcommand}"
		exitCode=$?
		set -e

		if [ "${exitCode}" == "0" ]; then
			eval "${helpcommand}"
		else
			echo "No help available for ${DKR_NAME} ${DKR_COMMAND}"
			exit 2
		fi
	else
		command="__dkr-${DKR_COMMAND}"
		shift
		eval "${command}" "$@"
	fi
else
	debug "Using vanilla docker"
	if [[ "$@" =~ '--help' ]]; then
		"${DKR_DOCKER_COMMAND}" "$@" | sed "s#Usage:\s*docker#Usage:  ${DKR_NAME}#g"
	else
		"${DKR_DOCKER_COMMAND}" "$@"
	fi
fi
