#!/bin/bash -e

if [ "${DKR_HOME}" == "" ]; then
	export DKR_HOME=~/.dkr
fi

function debug {
	if [ "${DKR_DEBUG}" != "" ]; then
		echo "$@" >&2
	fi
}

function err {
	echo "$@" >&2
}

function usage {
	echo "Dkr - Extendable docker cli wrapper"
	echo ""
	echo "Dkr exposes all the standard docker commands:"

	docker --help | head -n-2 | tail -n+5

	echo ""
	echo "Extensions:"
	echo ""

	for option in $(declare -F | grep -Eo "dkr-.*"); do
		if [[ "${option}" != *-summary_ ]]; then
			set +e
			2>/dev/null 1>/dev/null type "${option}-summary_"
			exitCode=$?
			set -e

			if [ "${exitCode}" == "0" ]; then
				echo "    ${option:4} - $(eval ${option}-summary_)"
			else
				echo "    ${option:4}"
			fi
		fi
	done

	echo ""
	echo "See README for more information on extending dkr"
}

for file in $(ls /usr/local/var/dkr/*); do
	if [[ -x ${file} ]]; then
		debug "Sourcing ${file}"
		source ${file}
	else
		debug "Skipping ${file}. Not Executable."
	fi
done

for file in $(ls ${DKR_HOME}/*); do
	if [[ -x ${file} ]]; then
		debug "Sourcing ${file}"
		source ${file}
	else
		debug "Skipping ${file}. Not Executable."
	fi
done

if [ "$1" == "" ]; then
	usage
	exit 1
fi

set +e
2>/dev/null 1>/dev/null type "dkr-$1"
exitCode=$?
set -e

if [ "$exitCode" == "0" ]; then
	command="dkr-$1"
	shift
	eval ${command} "$@"
else
	docker "$@"
fi
