#!/bin/bash

DKR_BIN_DIR_PATH=/usr/local/var/dkr
DKR_BIN_PATH=/usr/local/bin/dkr
DKR_HOME=~/.dkr
DKR_PROFILE=~/.profile
DKR_PROFILE_FILE=~/.dkrprofile
DKR_DOCKER_COMMAND="$(which docker)"

2>/dev/null 1>/dev/null grep '# ADDED BY DKR' "${DKR_PROFILE}"
if [ "$?" == "0" ]; then
	echo "Detected dkr was previously installed."
	installed=true
else
	installed=false
fi

# Older version of dkr installed by linking things. Make sure the links are gone.
2>/dev/null 1>/dev/null unlink "${DKR_BIN_DIR_PATH}"
2>/dev/null 1>/dev/null unlink "${DKR_BIN_PATH}"

rm -rf "${DKR_BIN_DIR_PATH}"
rm -f "${DKR_BIN_PATH}"

mkdir -p "${DKR_HOME}"
mkdir -p "${DKR_BIN_DIR_PATH}"

cp dkr "${DKR_BIN_PATH}"
cp home/* "${DKR_BIN_DIR_PATH}"

if [ "${installed}" != "true" ]; then
	echo "# ADDED BY DKR" >> ${DKR_PROFILE}
	echo "source \"${DKR_PROFILE_FILE}\"" >> ${DKR_PROFILE}
fi

# (Re)generate the DKR_PROFILE_FILE which should be sourced into the bash profile
echo "export DKR_HOME=\"${DKR_HOME}\"" > "${DKR_PROFILE_FILE}"
echo "export DKR_BIN_DIR_PATH=\"${DKR_BIN_DIR_PATH}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_BIN_PATH=\"${DKR_BIN_PATH}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_PROFILE=\"${DKR_PROFILE}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_PROFILE_FILE=\"${DKR_PROFILE_FILE}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_DOCKER_COMMAND=\"${DKR_DOCKER_COMMAND}\"" >> "${DKR_PROFILE_FILE}"

cat profileFile >> "${DKR_PROFILE_FILE}"

echo "Installed dkr to \"${DKR_BIN_PATH}\". You may need to restart your bash session or run:"
echo ""
echo "source \"${DKR_PROFILE_FILE}\""
echo ""