#!/bin/bash

DKR_BIN_DIR_PATH=/usr/local/var/dkr
DKR_BIN_PATH=/usr/local/bin/dkr
DKR_HOME=~/.dkr
DKR_PROFILE=~/.profile
DKR_PROFILE_FILE=~/.dkrprofile
DKR_DOCKER_COMMAND="$(which docker)"

if [ -f "${DKR_BIN_PATH}" ]; then
	installed=true
else
	installed=false
fi

2>/dev/null 1>/dev/null unlink "${DKR_BIN_DIR_PATH}"
rm -rf "${DKR_BIN_DIR_PATH}"

2>/dev/null 1>/dev/null unlink "${DKR_BIN_PATH}"
rm -f "${DKR_BIN_PATH}"

if [ ! -d "${DKR_HOME}" ]; then
	mkdir -p "${DKR_HOME}"
fi

mkdir -p "${DKR_BIN_DIR_PATH}"

cp dkr "${DKR_BIN_PATH}"
cp home/* "${DKR_BIN_DIR_PATH}"

if [ "${installed}" != "true" ]; then
	echo "source \"${DKR_PROFILE_FILE}\"" >> ${DKR_PROFILE}
fi

# (Re)generate the DKR_PROFILE_FILE which should be sourced into the bash profile
echo "export DKR_HOME=\"${DKR_HOME}\"" > "${DKR_PROFILE_FILE}"
echo "export DKR_BIN_DIR_PATH=\"${DKR_BIN_DIR_PATH}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_BIN_PATH=\"${DKR_BIN_PATH}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_PROFILE=\"${DKR_PROFILE}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_PROFILE_FILE=\"${DKR_PROFILE_FILE}\"" >> "${DKR_PROFILE_FILE}"
echo "export DKR_DOCKER_COMMAND=\"${DKR_DOCKER_COMMAND}\"" >> "${DKR_PROFILE_FILE}"

cat profileFile >> "${DKR_PROFILE_FILE}"

echo "Installed dkr to \"${DKR_BIN_PATH}\". You may need to restart your bash session or run:"
echo ""
echo "source \"${DKR_PROFILE_FILE}\""
echo ""