#!/bin/bash

export PATH="${DKR_HOME}":"${DKR_BIN_DIR_PATH}":"${PATH}"

if find "${DKR_BIN_DIR_PATH}" -mindepth 1 -print -quit | grep -q .; then
	for file in $(ls "${DKR_BIN_DIR_PATH}"/*); do
		if [[ ! -x ${file} ]]; then
			source ${file}
		fi
	done
fi

if find "${DKR_HOME}" -mindepth 1 -print -quit | grep -q .; then
	for file in $(ls "${DKR_HOME}"/*); do
		if [[ ! -x ${file} ]]; then
			source ${file}
		fi
	done
fi