#!/bin/bash

function __dkr_autocomplete {
    set +e
    local cur_command=${COMP_WORDS[1]}
    local cur=${COMP_WORDS[COMP_CWORD]}

    local commands=""
    if [ "${COMP_CWORD}" -gt 1 ]; then
        case "${cur}" in
            -* )
                commands=$(__listFlags ${cur_command})
                ;;
            * )
                "${DKR_BIN_PATH}" "${cur_command}" --help | grep -E "Usage:.*CONTAINER" 2>/dev/null 1>/dev/null
                if [ "$?" == 0 ]; then
                    commands=$(__all_containers)
                else
                    "${DKR_BIN_PATH}" "${cur_command}" --help | grep -E "Usage:.*IMAGE" 2>/dev/null 1>/dev/null
                    if [ "$?" == 0 ]; then
                        commands=$(__all_images)
                    fi
                fi
                ;;
        esac
    else
        commands=$(__listCommands)
    fi
    COMPREPLY=($(compgen -W '${commands[@]}' -- "$cur"))
    return 0
}

function __all_containers {
    for id in $("${DKR_DOCKER_COMMAND}" ps -aq); do
        name="$("${DKR_DOCKER_COMMAND}" inspect -f "{{.Name}}" ${id})"
        echo ${name:1}
    done
}

function __all_images {
    "${DKR_DOCKER_COMMAND}" images | awk '{ print $1":"$2 }' | sort | uniq
}

function __listCommands {
	"${DKR_BIN_PATH}" --help | grep -E "^\s+" | grep -vE "\s+-" | awk '{print $1}' | sort | uniq
}

function __listFlags {
	firstResult=$("${DKR_BIN_PATH}" $1 --help | grep -oE "^\s+-[a-zA-Z_-]*" | xargs )
	secondResult=$("${DKR_BIN_PATH}" $1 --help | grep -oE ",\s+-[a-zA-Z_-]*" | awk '{ print $2 }' | xargs )

	echo "${firstResult}
${secondResult}" | sort | uniq
}

complete -o default -F __dkr_autocomplete $(basename "${DKR_BIN_PATH}")
complete -o default -F __dkr_autocomplete "${DKR_BIN_PATH}"