#!/bin/bash

function __dkr-clean {
	if [[ "$@" =~ '--all' ]]; then
		containers=$("${DKR_DOCKER_COMMAND}" ps -a)
		2>/dev/null 1>/dev/null "${DKR_DOCKER_COMMAND}" stop ${containers}
	else
		containers=$("${DKR_DOCKER_COMMAND}" ps -a | grep -E "Exited .*? ago" | awk '{ print $1 }')
	fi

	containers=$("${DKR_DOCKER_COMMAND}" ps -a | grep -E "Exited .*? ago" | awk '{ print $1 }')
	if [ "$containers" != "" ]; then
		"${DKR_DOCKER_COMMAND}" rm ${containers}
	else
		echo "Nothing to clean"
	fi
}

function __dkr-clean-summary_ {
	echo "Deletes all stopped containers"
}

function __dkr-clean-help_ {
	echo ""
	echo "Usage:  ${DKR_NAME} clean"
	echo ""
	__dkr-clean-summary_
	echo ""
	echo "  --all=false        Stops and removes all contain"
	echo "  --help=false       Print usage"
}

export -f __dkr-clean
export -f __dkr-clean-summary_
export -f __dkr-clean-help_