#!/bin/bash

function dkr-cleani {
	if [[ "$@" =~ '--all' ]]; then
		images=$("${DKR_DOCKER_COMMAND}" images -q)
	else
		images=$("${DKR_DOCKER_COMMAND}" images -q -f dangling=true)
	fi

	if [ "${images}" != "" ]; then
		"${DKR_DOCKER_COMMAND}" rmi ${images}
	else
		echo "Nothing to clean"
	fi
}

function dkr-cleani-summary_ {
	echo "Cleans all dangling images"
}

function dkr-cleani-help_ {
	echo ""
	echo "Usage:  ${DKR_NAME} cleani"
	echo ""
	dkr-cleani-summary_
	echo ""
	echo "  --all=false        Deletes all images"
	echo "  --help=false       Print usage"
}

export -f dkr-cleani
export -f dkr-cleani-summary_
export -f dkr-cleani-help_