#!/bin/bash

function __dkr-portmap-summary_ {
	echo "Maps the currently running containers' ports to the host machine. (Requires a VirtualBox DockerMachine)"
}

function __dkr-portmap {
	machine_name="$(docker-machine ls | grep -E '\*' | awk '{ print $1 }')"

	if [ "${machine_name}" == "" ]; then
		err "No docker-machine selected. Run \`eval \"\$(docker-machine env \$machine_name)\""
		exit 1
	fi

	2>/dev/null 1>/dev/null VBoxManage showvminfo ${machine_name}
	if [ "$?" != 0 ]; then
		err "The current docker-machine selected (${machine_name}) is not a VirtualBox machine."
		exit 2
	fi

	debug "using dockermachine ${machine_name}"

	clear_old_docker_ports ${machine_name}
	add_new_docker_ports ${machine_name}
}

function clear_old_docker_ports {
	set +e
	debug "clearing old docker ports"
	portsToDelete=$(VBoxManage showvminfo $1 --details | grep -o 'docker-sync-port-[0-9][0-9]*')

	for portToDelete in ${portsToDelete}; do
		debug "deleting port: ${portToDelete}"
		VBoxManage controlvm $1 natpf1 delete ${portToDelete}
	done
	set -e
}

function add_new_docker_ports {
	debug "adding new docker ports"

	set +e
	count=0
	for containerId in $(docker ps -q); do
		containerName="$(docker inspect --format '{{.Name}}' ${containerId})"

		IFS='
'
		for line in $("${DKR_DOCKER_COMMAND}" port ${containerId}); do
			count=$((count+1))
			hostPortAndType=$(echo ${line} | awk '{ print $1 }')
			guestIpAndPort=$(echo ${line} | awk '{ print $3 }')

			hostPort=$(echo ${hostPortAndType} | awk -F'/' '{ print $1 }')
			forwardType=$(echo ${hostPortAndType} | awk -F'/' '{ print $2 }')
			guestPort=$(echo ${guestIpAndPort} | awk -F':' '{ print $2 }')

			if [ "${guestPort}" -lt 1024 ]; then
				err "forwarding port: ${guestPort} (${hostPort}) for ${containerName:1} (Privileged port. May not work.)"
			else
				err "forwarding port: ${guestPort} (${hostPort}) for ${containerName:1}"
			fi


			VBoxManage controlvm $1 natpf1 "docker-sync-port-$count,${forwardType},0.0.0.0,${guestPort},,${guestPort}"
		done
	done
	set -e
}

function __dkr-portmap-help_ {
	echo ""
	echo "Usage:  ${DKR_NAME} portmap"
	echo ""
	__dkr-portmap-summary_
	echo ""
	echo "  --help=false       Print usage"
}

export -f __dkr-portmap
export -f __dkr-portmap-summary_
export -f __dkr-portmap-help_