#!/bin/bash

function __dkr-rm {
	force=false
	params=""
	while [ "$1" != "" ]; do
		case "$1" in
			-f)
				force=true
				;;
			--force)
				force=true
				;;
			-)
				params="${params} $("${DKR_DOCKER_COMMAND}" ps --latest --quiet)"
				;;
			-*)
				err "Unknown flag: $1"
				exit 1
				;;
			*)
				params="${params} $1"
		esac
		shift
	done

	if [ "${params}" == "" ]; then
		params="${params} $("${DKR_DOCKER_COMMAND}" ps --all --quiet)"
	fi

	if [ "${force}" != "true" ]; then
		echo "Are you sure you want to stop and delete the following containers?"
		for name in ${params}; do
			containerId="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Id}}' ${name})"
			containerName="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Name}}' ${name})"

			echo "    ${containerName:1} (${containerId:0:12})"
		done
		read -p "[y/N] " yn
		case ${yn} in
			[Yy]* )
				;;
			* )
				echo "Nothing removed"
				exit 0
				;;
		esac
	fi

	for name in ${params}; do
		inspect="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Id}}:{{.Name}}' ${name})"
		containerId=$(echo "${inspect}" | awk -F':' '{print $1}')
		containerName=$(echo "${inspect}" | awk -F':' '{print $2}')

		"${DKR_DOCKER_COMMAND}" stop "${containerId}" > /dev/null
		"${DKR_DOCKER_COMMAND}" rm "${containerId}" > /dev/null
		echo "Removed: ${containerName:1} (${containerId:0:12})"
	done
}

function __dkr-rm-summary_ {
	echo "Stops and deletes the listed containers"
}


function __dkr-rm-help_ {
	echo ""
	echo "Usage:  ${DKR_NAME} rm [CONTAINER, ...]"
	echo ""
	__dkr-rm-summary_
	echo ""
	echo "If no parameters are specified, you will be prompted if you want to stop and delete all containers."
	echo "If parameters are specified, then you will be prompted if you want to stop and delete all of them."
	echo ""
	echo "  -f=false           Force stop and delete. Do not prompt for deletion."
	echo "  --help=false       Print usage"
}
