#!/bin/bash -e

function dkr-rm {
	params="$@"
	if [ "${params}" == "" ]; then
		params="$("${DKR_DOCKER_COMMAND}" ps -aq)"
	fi

	if [ "$1" == "-f" ]; then
		shift
		for name in ${params}; do
			containerId="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Id}}' ${name})"
			containerName="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Name}}' ${name})"
			"${DKR_DOCKER_COMMAND}" stop "${containerId}" > /dev/null
			"${DKR_DOCKER_COMMAND}" rm "${containerId}" > /dev/null
			echo "Removed: ${containerName:1} (${containerId:0:12})"
		done
	else
		echo "Are you sure you want to stop and delete the following containers?"
		for name in ${params}; do
			containerId="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Id}}' ${name})"
			containerName="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Name}}' ${name})"

			echo "    ${containerName:1} (${containerId:0:12})"
		done
		read -p "[y/N] " yn
		case ${yn} in
			[Yy]* )
				for name in ${params}; do
					containerId="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Id}}' ${name})"
					containerName="$(${DKR_DOCKER_COMMAND} inspect --format '{{.Name}}' ${name})"
					"${DKR_DOCKER_COMMAND}" stop "${containerId}" > /dev/null
					"${DKR_DOCKER_COMMAND}" rm "${containerId}" > /dev/null
					echo "Removed: ${containerName:1} (${containerId:0:12})"
				done
				;;
			* )
				echo "Nothing removed"
				;;
		esac
	fi
}

function dkr-rm-summary_ {
	echo "Stops and deletes the listed containers"
}


function dkr-rm-help_ {
	echo ""
	echo "Usage:  ${DKR_NAME} rm [CONTAINER ID OR NAME, ...]"
	echo ""
	dkr-rm-summary_
	echo ""
	echo "If no parameters are specified, you will be prompted if you want to stop and delete all containers."
	echo "If parameters are specified, then you will be prompted if you want to stop and delete all of them."
	echo ""
	echo "  -f=false           Force stop and delete. Do not prompt for deletion."
	echo "  --help=false       Print usage"
}