#!/bin/bash

function dkr-rn {
	set -m
	"${DKR_DOCKER_COMMAND}" run "$@" &
	2>/dev/null 1>/dev/null dkr-portmap

	if [ "$?" != "0" ]; then
		err "Could not map ports\!"
	fi

	2>/dev/null 1>/dev/null fg
}

function dkr-rn-summary_ {
	echo "Runs like normal, and then immediately re-maps all the docker ports"
}

function dkr-rn-help_ {
	"${DKR_DOCKER_COMMAND}" run --help | sed "s#Usage:\s*docker run#Usage:  ${DKR_NAME} rn#g"
	echo ""
	dkr-rn-summary_
}

export -f dkr-rn
export -f dkr-rn-summary_
export -f dkr-rn-help_